import type { DigestItem, Source, InterestProfile, DigestSettings } from "./types"

export const mockDigestItems: DigestItem[] = [
  {
    id: "1",
    type: "article",
    title: "The Future of Urban Infrastructure: How Cities Are Adapting to Climate Change",
    source: "Brookings Institution",
    author: "Sarah Chen",
    url: "https://example.com/article-1",
    publishedAt: new Date("2026-03-16T08:00:00"),
    summary: "A comprehensive analysis of how major American cities are investing in resilient infrastructure to combat rising temperatures and extreme weather events. The report highlights innovative approaches from Philadelphia, Phoenix, and Seattle.",
    relevanceScore: 95,
    tags: ["essay", "newsletter"],
  },
  {
    id: "2",
    type: "article",
    title: "Economic Development in the Rust Belt: A New Manufacturing Renaissance",
    source: "The Atlantic",
    author: "Marcus Rodriguez",
    url: "https://example.com/article-2",
    publishedAt: new Date("2026-03-16T06:30:00"),
    summary: "Ohio, Michigan, and Pennsylvania are experiencing a resurgence in advanced manufacturing, driven by EV battery plants and semiconductor fabs. This shift is reshaping local economies and workforce dynamics.",
    relevanceScore: 92,
    tags: ["essay"],
  },
  {
    id: "3",
    type: "tweet",
    title: "@urbanplanner: \"New study shows that walkable neighborhoods increase property values by 23% while reducing healthcare costs. The data is clear: density pays dividends.\"",
    source: "Twitter/X",
    author: "@urbanplanner",
    url: "https://twitter.com/example",
    publishedAt: new Date("2026-03-16T07:15:00"),
    summary: "Viral thread discussing the economic benefits of walkable urban design, citing new research from MIT's Center for Real Estate.",
    relevanceScore: 88,
    tags: ["social"],
  },
  {
    id: "4",
    type: "article",
    title: "Why Institutional Reform Matters More Than Policy",
    source: "Niskanen Center",
    author: "Dr. James Wright",
    url: "https://example.com/article-4",
    publishedAt: new Date("2026-03-15T14:00:00"),
    summary: "An argument for focusing on institutional design rather than specific policies. Wright contends that well-designed institutions can self-correct over time, while poorly designed ones will corrupt even good policies.",
    relevanceScore: 86,
    tags: ["essay", "newsletter"],
  },
  {
    id: "5",
    type: "article",
    title: "The Hidden Costs of Remote Work on Urban Economies",
    source: "City Journal",
    author: "Elizabeth Park",
    url: "https://example.com/article-5",
    publishedAt: new Date("2026-03-15T10:00:00"),
    summary: "Downtown areas in mid-sized cities are struggling to adapt to permanent remote work patterns. This analysis examines the fiscal implications for municipal budgets dependent on commercial property taxes.",
    relevanceScore: 84,
    tags: ["newsletter"],
  },
  {
    id: "6",
    type: "tweet",
    title: "@pikicontrarian: \"The real story in the housing market isn't prices—it's the collapse of new construction permits in the Midwest. Thread with charts.\"",
    source: "Twitter/X",
    author: "@pikicontrarian",
    url: "https://twitter.com/example-2",
    publishedAt: new Date("2026-03-15T16:45:00"),
    summary: "Data-driven analysis showing how regulatory barriers and labor shortages are constraining housing supply in key metropolitan areas.",
    relevanceScore: 81,
    tags: ["social", "newsletter"],
  },
  {
    id: "7",
    type: "article",
    title: "Public Transit Ridership Surges Past Pre-Pandemic Levels in Select Cities",
    source: "Transportation Research Board",
    author: "Michael Torres",
    url: "https://example.com/article-7",
    publishedAt: new Date("2026-03-15T09:00:00"),
    summary: "Detailed analysis of which transit systems have recovered and why. Frequency, safety improvements, and fare policy emerge as key differentiators.",
    relevanceScore: 79,
    tags: ["essay"],
  },
  {
    id: "8",
    type: "article",
    title: "The Case for Regional Governance in Metropolitan Areas",
    source: "Urban Institute",
    author: "Dr. Linda Okonkwo",
    url: "https://example.com/article-8",
    publishedAt: new Date("2026-03-14T11:00:00"),
    summary: "Fragmented local governments create coordination failures in transportation, housing, and economic development. This paper proposes models for voluntary regional cooperation.",
    relevanceScore: 77,
    tags: ["essay", "newsletter"],
  },
  {
    id: "9",
    type: "article",
    title: "How Small Towns Are Winning the Remote Worker Migration",
    source: "Bloomberg CityLab",
    author: "Jessica Huang",
    url: "https://example.com/article-9",
    publishedAt: new Date("2026-03-14T08:30:00"),
    summary: "Case studies from Tulsa, Bentonville, and Chattanooga show how strategic incentive programs and quality-of-life investments attract high-income remote workers.",
    relevanceScore: 75,
    tags: ["newsletter"],
  },
  {
    id: "10",
    type: "tweet",
    title: "@economichistory: \"Fascinating archival finding: the 1950s highway program was explicitly designed to break up urban neighborhoods. Internal memos show this was the primary goal.\"",
    source: "Twitter/X",
    author: "@economichistory",
    url: "https://twitter.com/example-3",
    publishedAt: new Date("2026-03-14T19:20:00"),
    summary: "Historian shares primary source documents revealing the intentional displacement effects of interstate highway construction through American cities.",
    relevanceScore: 73,
    tags: ["social"],
  },
]

export const mockSources: Source[] = [
  { id: "1", name: "Brookings Institution", url: "https://brookings.edu/feed", type: "rss", category: "Think Tanks", enabled: true, lastFetched: new Date() },
  { id: "2", name: "The Atlantic", url: "https://theatlantic.com", type: "website", category: "Magazines", enabled: true, lastFetched: new Date() },
  { id: "3", name: "Niskanen Center", url: "https://niskanencenter.org/feed", type: "rss", category: "Think Tanks", enabled: true, lastFetched: new Date() },
  { id: "4", name: "City Journal", url: "https://city-journal.org", type: "website", category: "Policy", enabled: true, lastFetched: new Date() },
  { id: "5", name: "Bloomberg CityLab", url: "https://bloomberg.com/citylab", type: "rss", category: "Urban Policy", enabled: true, lastFetched: new Date() },
  { id: "6", name: "Urban Institute", url: "https://urban.org/feed", type: "rss", category: "Think Tanks", enabled: true, lastFetched: new Date() },
  { id: "7", name: "@urbanplanner", url: "https://twitter.com/urbanplanner", type: "twitter", category: "Twitter/X", enabled: true, lastFetched: new Date() },
  { id: "8", name: "@pikicontrarian", url: "https://twitter.com/pikicontrarian", type: "twitter", category: "Twitter/X", enabled: true, lastFetched: new Date() },
  { id: "9", name: "Transportation Research Board", url: "https://trb.org/feed", type: "rss", category: "Research", enabled: false, lastFetched: new Date() },
  { id: "10", name: "Strong Towns", url: "https://strongtowns.org", type: "rss", category: "Urban Policy", enabled: true, lastFetched: new Date() },
]

export const mockInterestProfile: InterestProfile = {
  topics: [
    "Urban policy",
    "Economic development", 
    "Infrastructure",
    "Institutional analysis",
    "Housing policy",
    "Transportation",
    "Local government",
  ],
  geographicFocus: [
    "United States",
    "American Midwest",
    "Rust Belt cities",
    "Mid-sized metros",
  ],
  authors: [
    "Edward Glaeser",
    "Alain Bertaud",
    "Devon Zuegel",
    "Jerusalem Demsas",
  ],
  keywords: [
    "zoning reform",
    "YIMBY",
    "transit-oriented development",
    "fiscal federalism",
    "state capacity",
    "regulatory reform",
  ],
  description: "I write about urban policy, economic development, and institutional design with a focus on the American Midwest. I'm interested in how cities can become more productive, livable, and fiscally sustainable. My newsletter covers policy debates and research findings relevant to practitioners and engaged citizens.",
}

export const mockSettings: DigestSettings = {
  maxItems: 25,
  relevanceThreshold: 70,
  deliveryTime: "07:00",
  email: "user@example.com",
}
